server:
  port: 9210
spring:
  application:
    name: parent-consumer-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-center:9101/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
